### ISSUE TITLE
Bot syntax checker

### ISSUE THREAD

**Issue by msfjarvis** [elonusbot/bot.py#3]
The bot needs Travis-CI to check it's JSON file(s) through a lint and it's Python files using a syntax checker. Both these functions have been coded into CloudBotIRC's latest IRC bot, and the Travis-CI build logs can be accessed [here](https://travis-ci.org/CloudBotIRC/CloudBot)

**Comment by thewisenerd** [comment]
sure their json testing and pytest are available ;) 

what exactly do they do?
